version: '3.8'

services:
  llama-api:
    build:
      context: api-stuff
      dockerfile: Dockerfile
    ports:
      - "8052:8052"
    command: python /api-stuff/llama-api.py --port=8052

  login-api:
    build:
      context: api-stuff
      dockerfile: Dockerfile
    ports:
      - "8053:8053"
    command: python /api-stuff/login-api.py --port=8053
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: school_db                
      MYSQL_USER: aroteo                   
      MYSQL_PASSWORD: aroteo   
    volumes:
      - ./mariadb_funny/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "3306:3306"

  web-server:
    image: nginx:latest
    volumes:
      - ./html-stuff:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
